FROM golang:1.21-alpine as base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main cmd/api/main.go

FROM alpine:3.19.0 as prod
WORKDIR /app
COPY --from=base /app/main /app/main
COPY cmd/web cmd/web
COPY internal/database/migrations internal/database/migrations
EXPOSE ${PORT}
CMD ["./main"]