FROM golang:1.22.1-alpine as base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main cmd/api/main.go

FROM alpine:3.19.0 as prod
WORKDIR /app
COPY --from=base /app/main /app/main
COPY cmd/web cmd/web
COPY internal/database/migrations internal/database/migrations
EXPOSE ${PORT}
CMD ["./main"]

FROM base as migrate
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
CMD ["goose", "-dir", "./internal/database/migrations", "up"]